#!/bin/bash
NAZWA=$1
#-e (obojetnie, -f (plik) -d (folder)
# else if = elif
# -eq : ==
# -ne : not equal
# -gt : greater than
# -lt : less then
# -ge : great equal
# -le : less equal
# -z : ciag znakow pusty
# -n : niepusty

#find // grep
#find ... -exec grep ... {} \;

PLIK="";
KATALOG="";
CMD=0;
CALOSC="";
OPCJA1="";
OPCJA2="";
ZAWARTOSC="";

EX=1;

while [ $EX ]; do
	echo "1. nazwa pliku: $PLIK";
	echo "2. katalog: $KATALOG";
	echo "3. prawa dostepu: $OPCJA1";
	echo "4. ile dni temu: $OPCJA2";
	echo "5. zawartosc: $ZAWARTOSC";
	echo "6. szukaj";
	echo "7. koniec";
	read CMD
	
	if [ $CMD -eq 1 ]; then
		read PLIK;
	elif [ $CMD -eq 2 ]; then
		read KATALOG;
	elif [ $CMD -eq 3 ]; then
		read OPCJA1;
	elif [ $CMD -eq 4 ]; then
		read OPCJA2;
	elif [ $CMD -eq 5 ]; then
		read ZAWARTOSC;
	elif [ $CMD -eq 6 ]; then
		
		EXIST=`find $KATALOG -name $PLIK -perm $OPCJA1 -mtime $OPCJA2 -exec grep $ZAWARTOSC {}  \;`
		if [ -n $EXIST ]; then
			echo "plik istnieje";
		else
			echo "plik nie istnieje";
		fi

	elif [ $CMD -eq 7 ]; then
		((EX--));
		exit 0;
	fi
done
