#!/bin/bash
CMD=0
menu=("Nazwa pliku" "Sciezka do pliku" "Min rozmiar" "Max rozmiar" "Zawartosc" "Szukaj")

while [ $CMD -ne 7 ];do

	CMD=$(zenity --list --height 360 --cancel-label "KONIEC" --ok-label "Wybierz opcję" --column="Menu główne" "${menu[@]}")

	if [[ $? -eq 1 ]]; then
	    echo "koniec"
	    break
	fi

#echo "1. Nazwa pliku: $PLIK
#2. Sciezka do pliku: $KATALOG
#3. Min rozmiar: $MIN
#4. Max rozmiar: $MAX
#5. Zawartosc: $ZAW
#6. Szukaj
#7. Koniec"

	echo $CMD

	if [ "$CMD" = "Nazwa pliku" ];then
	PLIK=`zenity --entry --title "Nazwa pliku:" --text "komunikat"`
	CMD=0

	elif [ "$CMD" = "Sciezka do pliku" ];then
	KATALOG=`zenity --entry --title "Sciezka do pliku:" --text "komunikat"`
	CMD=0

	elif [ "$CMD" = "Min rozmiar" ];then
	MIN`zenity --entry --title "c/k/M/G (rozmiar):" --text "komunikat"`
	CMD=0
	
	elif [ "$CMD" = "Max rozmiar" ];then
	MAX=`zenity --entry --title "c/k/M/G (rozmiar):" --text "komunikat"`
	CMD=0

	elif [ "$CMD" = "Zawartosc" ];then
	ZAW=`zenity --entry --title "Zawartosc:" --text "komunikat"`
	CMD=0

	elif [ "$CMD" = "Szukaj" ];then
	WYNIK=$(find $KATALOG -name $PLIK -size "+$MIN" -size "-$MAX" -exec grep -l $ZAW {} \; |& grep -v "Brak dostępu" | wc -l)
		if [ $WYNIK -gt 0 ];then
		zenity --info --title "tytuł" --text "plik istnieje"
		else
		zenity --info --title "tytuł" --text "plik nie istnieje"
		fi
	CMD=0

	else echo "-----------------"
	fi
	done
